config/routes.rb
Rails.application.routes.draw do
  # resources :votes
  resources :memos
  resources :lists
  resources :sample_sales
  root to: 'home#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :lists, only: [:index] do
    resources :sample_sales, only: [:show]
  end
  post "/add_to_list" => 'lists#create'
  get "/like" => 'sample_sales#like'
  get "/dislike" => 'sample_sales#dislike'
  get "/sort_by_likes" => 'sample_sales#sort_by_likes'
  get "/sort_by_dates" => 'lists#sort_by_dates'
  
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :sample_sale
  has_one :memo
  has_many :sample_sale_lists
  has_many :sample_sales, through: :sample_sale_lists

  def self.create_from_sample_sales(user_id, ids)
    ids.map do |id|
      List.find_or_create_by(user_id: user_id, sample_sale_id: id)
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    if !current_user
      redirect_to new_user_session_path
    else
      if params[:sample_sales_ids] || current_user.lists
        if params[:sample_sales_ids]
          @lists = List.create_from_sample_sales(current_user.id, params[:sample_sales_ids]) 
        else
          @lists = current_user.lists 
        end
        redirect_to lists_path
      else
        redirect_to sample_sales_path 
      end
    end
  end

  def index
    @lists = current_user.lists if current_user.lists
    @memo ? @memo : Memo.new
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    List.delete(params[:id])
    redirect_to lists_path
  end

  def sort_by_dates
    @lists = current_user.lists.sort do |a, b|
      a.sample_sale.dates <=> b.sample_sale.dates
    end
    render '/lists/index'
  end
  
  private

    def list_params
      params.require(:list).permit(:user_id, sample_sales_ids:[])
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(list.memo||Memo.new) do |f| %>
  <%= f.hidden_field 'list_id', :value => list.id %>
  <%= f.hidden_field 'id', :value => list.memo.id  if list.memo %>
  <%= f.text_area :content, :placeholder => "update a memo", :rows => 2, :cols => 30 %>
  <%= f.submit "Create", class:"btn btn-default btn-sm btn-success" if !list.memo %>

  <div class="btn btn-group editDelete">
  <%= f.submit "Edit", class:"btn btn-default btn-sm btn-info" if list.memo %>
<% end %>
  <%= button_to "Delete", memo_path(list.memo), method: :delete, class:"btn btn-default btn-sm btn-danger" if list.memo %> 
 </div>

app/views/lists/_list.html.erb
<td><%= link_to list.sample_sale.brand, list_sample_sale_path(list, list.sample_sale)%></td>
<td><%= link_to list.sample_sale.about, list_sample_sale_path(list, list.sample_sale)%></td>
<td><%= link_to list.sample_sale.dates, list_sample_sale_path(list, list.sample_sale)%></td>
<td><%= link_to list.sample_sale.hours, list_sample_sale_path(list, list.sample_sale)%></td>
<td><%= link_to list.sample_sale.address, list_sample_sale_path(list, list.sample_sale)%></td>

app/views/lists/index.html.erb
<div class="list">
  <h1 class="center" style="margin-top: 70px">Your Sample Sale List</h1>
  <br>

  <div class="table-box2 centered-box2">
    <div class="btn-group right">
      <%= link_to "Sort By Dates", sort_by_dates_path, method: :get, class:"btn btn-default" %>
      <%= link_to "Sort By Default", lists_path, method: :get, class:"btn btn-default" %>  
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th><strong>Brand</strong></th>
          <th><strong>About</strong></th>
          <th><strong>Dates</strong></th>
          <th><strong>Hours</strong></th>
          <th><strong>Address</strong></th>
          <th><strong>Memo</strong></th>
          <th><strong>Delete</strong></th>
        </tr>
      </thead>

      <tbody>
        <% @lists.each do |list| %>
        <tr>
          <%= render partial: "list", locals: {list: list} %> 
          <td>
            <%= render partial: "form", locals: {list: list} %>                
          </td>

          <td>
            <%= button_to "X", list_path(list), method: :delete, class:"btn btn-default btn-sm btn-danger delete" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>

</div>