config/routes.rb
Rails.application.routes.draw do
  # resources :votes
  resources :memos
  resources :lists
  resources :sample_sales
  root to: 'home#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :lists, only: [:index] do
    resources :sample_sales, only: [:show]
  end
  post "/add_to_list" => 'lists#create'
  get "/like" => 'sample_sales#like'
  get "/dislike" => 'sample_sales#dislike'
  get "/sort_by_likes" => 'sample_sales#sort_by_likes'
  get "/sort_by_dates" => 'lists#sort_by_dates'
  
end

app/models/sample_sale.rb
class SampleSale < ApplicationRecord
  has_many :sample_sale_lists
  has_many :lists, through: :sample_sale_lists
  has_many :users, through: :lists
  has_many :votes
  
  def self.of_the_week
    sales_of_the_week = []
    SampleSale.all.collect do |s|
      s.dates.gsub!('/','-')
      # start_date = '2016-'+ s.dates[0..4]
      end_date = '2016-' + s.dates[-5..-1]   
      sales_of_the_week << s if Date.parse(end_date) >= Date.today && Date.parse(end_date) < (Date.today + 7.days)  
    end
    sales_of_the_week
  end

  # def added_to_list?(id)
  #   List.find_by(sample_sale_id: self.id, user_id: id)
  # end

  def total_likes
    self.votes.inject(0){|sum, v| sum + v.like }
  end

  def total_dislikes
    self.votes.inject(0){|sum, v| sum + v.dislike }
  end

  def current_like(id)
    @vote = self.votes.find_by(user_id: id)
    @vote ? @vote.like : 0
  end

  def current_dislike(id)
    @vote = self.votes.find_by(user_id: id)
    @vote ? @vote.dislike : 0
  end

  def self.sort_by_likes
    SampleSale.all.sort do |a, b|
      b.total_likes <=> a.total_likes
    end
  end

  def is_not_in_lists_of(current_user)
    !current_user || !(current_user.lists.any?{|x| x.sample_sale == self})
  end

end

app/controllers/sample_sales_controller.rb
class SampleSalesController < ApplicationController
  def index
    @sample_sales = SampleSale.all 
    @list = List.new
  end

  def show
    if current_user
      @sample_sale = SampleSale.find(params[:id])
    else
      flash[:error] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path
    end
  end

  # def add_to_list
  #   if !current_user
  #     redirect_to new_user_session_path
  #   else
  #     if params[:sample_sales_ids] || current_user.lists
  #       if params[:sample_sales_ids]
  #         @list = List.create_from_sample_sales(current_user.id, params[:sample_sales_ids]) 
  #       else
  #         @list = current_user.lists 
  #       end
  #       redirect_to lists_path
  #     else
  #       redirect_to sample_sales_path 
  #     end
  #   end
  # end

  def sort_by_likes
    @sample_sales = SampleSale.sort_by_likes
    @list = List.new
    render '/sample_sales/index'
  end

  def like
    if current_user
      get_vote

      if @vote.like == 0 && @vote.dislike != -1
        @vote.like += 1
      elsif @vote.like == 1 
        @vote.like -= 1 
      end
      @vote.save

      redirect_to sample_sales_path
    else 
      flash[:error] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path
    end
  end

  def dislike
    if current_user
      get_vote
      
      if @vote.dislike == 0 && @vote.like != 1
        @vote.dislike -= 1 
      elsif @vote.dislike == -1 
        @vote.dislike += 1  
      end
      @vote.save

      redirect_to sample_sales_path
    else
      flash[:error] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path
    end

  end

private

  def get_vote
    sample_sale = SampleSale.find(params[:sample_sale])
    @vote = sample_sale.votes.find_by(user_id: current_user.id)
    unless @vote
      @vote = Vote.create(sample_sale_id: sample_sale.id, user_id: current_user.id)
      sample_sale.votes << @vote
    end
  end


end

app/helpers/sample_sales_helper.rb
module SampleSalesHelper

  def checked?(user, sample_sale)
    user && sample_sale.added_to_list?(user) ? true : false
  end
  
end

app/views/sample_sales/_dislike.html.erb
<% if current_user %>
  <% if sample_sale.current_dislike(current_user.id) > -1 %>
    <%= link_to "", dislike_path(sample_sale: sample_sale), method: :get, class:"fa fa-thumbs-o-down dislike_before" %>
  <% else %>
    <%= link_to "", dislike_path(sample_sale: sample_sale), method: :get, class:"fa fa-thumbs-down dislike_after" %>
  <% end %>
<% else %>
  <%= link_to "", dislike_path(sample_sale: sample_sale), class:"fa fa-thumbs-o-down dislike_before" %>
<% end %> 

app/views/sample_sales/_like.html.erb
<% if current_user %>
  <% if sample_sale.current_like(current_user.id) < 1 %>
    <%= link_to "", like_path(sample_sale: sample_sale), method: :get, class:"fa fa-thumbs-o-up center like_before" %>                 
  <% else %>
    <%= link_to "", like_path(sample_sale: sample_sale), method: :get, class:"fa fa-thumbs-up center like_after" %>
  <% end %>
<% else %>
  <%= link_to "", like_path(sample_sale: sample_sale), class:"fa fa-thumbs-o-up center like_before" %>
<% end %>

app/views/sample_sales/_link.html.erb
<td><%= link_to sample_sale.brand, sample_sale_path(sample_sale) %></td>
<td><%= link_to sample_sale.dates, sample_sale_path(sample_sale) %></td>
<td><%= link_to sample_sale.address, sample_sale_path(sample_sale) %></td>

app/views/sample_sales/index.html.erb
<h1 class="center" style="margin-top: 40px">Summer Sample Sales in NYC</h1>
<br>

<div class="table-box centered-box2">

  <table class="table table-hover">
    <thead class="thead-inverse">
      <tr>
        <th>#</th>
        <th>Brand</th>
        <th>Dates</th>
        <th>Address</th>
        <th>Like</th>
        <th>Total</th>
        <th>Dislike</th>
        <th>Total</th>
      </tr>
    </thead>
    
    <tbody>
      <%= form_for @list, url: lists_path do |f|%>
        <% @sample_sales.each do |sample_sale| %>
      <tr>
        <td scope="row">
          <% if  sample_sale.is_not_in_lists_of(current_user) %>
            
            <%= check_box_tag "sample_sales_ids[]", sample_sale.id %>
          <% end %>
        </td>
       
          <%= render partial: "link", locals: {sample_sale: sample_sale} %>

        <td>
          <%= render partial: "like", locals: {sample_sale: sample_sale} %>
        </td>

        <td class="total"><%= sample_sale.total_likes %></td>

        <td>
          <%= render partial: "dislike", locals: {sample_sale: sample_sale} %>   
        </td>

        <td class="total2"><%= sample_sale.total_dislikes %></td>
        
      </tr>
        <% end %>
        <div class="left"> 
          <%= f.submit "Add to my list", class:"btn btn-default addToList"%>
        </div>
      <% end %>

      <div class="btn-group right">
          <%= link_to "Sort By Dates", sample_sales_path, method: :get, class:"btn btn-default"%>
          <%= link_to "Sort By Likes", sort_by_likes_path, method: :get, class:"btn btn-default"%>    
      </div>

    </tbody>
  </table>

</div>

app/views/sample_sales/show.html.erb
<style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 100% }
  </style>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1NNKu1rO9MK6lm3SuhhhEEmgJx3PEpU4">
  </script>

<!-- <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>  -->
<!-- only if you need custom infoboxes -->
<%= yield :javascripts %>


<div class="center brand">
  <%= @sample_sale.brand %>
</div>
<div class="list-group centered-box4 table-box3">
  <table class="table ">
    <thead>
      <tr>
        <th class="center"><strong>About</strong></th>
        <th class="center"><strong>Dates</strong></th>
        <th class="center"><strong>Hours</strong></th>
        <th class="center"><strong>Address</strong></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @sample_sale.about %></td>
        <td><%= @sample_sale.dates %></td>
        <td><%= @sample_sale.hours %></td>
        <td id="address"><%= @sample_sale.address%></td>
      </tr>
      <tr>
        <td colspan="4">
            <div id="map" style='width: 100%; height: 400px;'></div>
        </td>
        
      </tr>

    </tbody>
  </table>
</div>

<script type="text/javascript">
      var geocoder = new google.maps.Geocoder();
      var address = document.getElementById('address').innerHTML + ' new york';

      var myLatLng = {lat: -25.363, lng: 131.044};
      var mapOptions = {
        center: new google.maps.LatLng(myLatLng),
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map"), mapOptions);

      geocoder.geocode({'address': address}, function(results, status) {
        if (status === 'OK') {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
          });
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
         
</script>





    